/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package edu.ctu.cit.sudoku.Views;

import edu.ctu.cit.sudoku.Controllers.PuzzleBoardController;
import edu.ctu.cit.sudoku.Models.Puzzle;

/**
 *
 * @author charlie
 */
public class ManuallyNewGameDialog extends javax.swing.JDialog {
    public interface OnUserPressOk {
        public void onUserPressOk(Puzzle puzzle);
    }
    
    public interface OnUserPressCancel {
        public void onUserPressCancel();
    }

    /** Creates new form ManuallyNewGameDialog */
    public ManuallyNewGameDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        getContentPane().add(this.controller.getPuzzleBoard(), java.awt.BorderLayout.CENTER);
        this.controller.setRepeatedCellCheck(true);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMain = new javax.swing.JPanel();
        buttonOk = new javax.swing.JButton();
        buttonCancel = new javax.swing.JButton();

        setAutoRequestFocus(false);
        setModal(true);
        setPreferredSize(new java.awt.Dimension(300, 300));

        panelMain.setLayout(new java.awt.GridBagLayout());

        buttonOk.setText("Ok");
        buttonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOkActionPerformed(evt);
            }
        });
        panelMain.add(buttonOk, new java.awt.GridBagConstraints());

        buttonCancel.setText("Cancel");
        buttonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelActionPerformed(evt);
            }
        });
        panelMain.add(buttonCancel, new java.awt.GridBagConstraints());

        getContentPane().add(panelMain, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOkActionPerformed
        if (onUserPressOk != null) {
            onUserPressOk.onUserPressOk(controller.getPuzzleBoard().getPuzzleUserAnswer());
        }
        this.dispose();
    }//GEN-LAST:event_buttonOkActionPerformed

    private void buttonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelActionPerformed
        if (onUserPressCancel != null) {
            onUserPressCancel.onUserPressCancel();
        }
        this.dispose();
    }//GEN-LAST:event_buttonCancelActionPerformed

    public void setOnUserPressOk(OnUserPressOk onUserPressOk) {
        this.onUserPressOk = onUserPressOk;
    }

    public void setOnUserPressCancel(OnUserPressCancel onUserPressCancel) {
        this.onUserPressCancel = onUserPressCancel;
    }
    
    private final PuzzleBoardController controller = new PuzzleBoardController(this);    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancel;
    private javax.swing.JButton buttonOk;
    private javax.swing.JPanel panelMain;
    // End of variables declaration//GEN-END:variables

    private OnUserPressOk onUserPressOk;
    private OnUserPressCancel onUserPressCancel;
}
