/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ctu.cit.sudoku.Views;

import edu.ctu.cit.sudoku.Factories.PuzzleFactory;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Collection;
import java.util.Collections;
import javax.swing.JButton;

/**
 *
 * @author charlie
 */
public class NewGameDialog extends javax.swing.JDialog {

    public interface OnGameDifficultiesSelected {
        public void onGameDifficultiesSelected(PuzzleFactory.GameDifficulties difficulties);
    }
    
    /**
     * Creates new form NewGameDialog
     */
    public NewGameDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.buttons = new JButton[]{
            buttonNewGameExtremelyEasy,
            buttonNewGameEasy,
            buttonNewGameMedium,
            buttonNewGameDifficult,
            buttonNewGameEvil,
        };
        
        for (int i = 0; i < this.buttons.length; i++) {
            final int index = i;
            buttons[i].addActionListener(evt -> this.buttonClicked(index));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonNewGameExtremelyEasy = new javax.swing.JButton();
        buttonNewGameEasy = new javax.swing.JButton();
        buttonNewGameMedium = new javax.swing.JButton();
        buttonNewGameDifficult = new javax.swing.JButton();
        buttonNewGameEvil = new javax.swing.JButton();
        lable = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setType(java.awt.Window.Type.UTILITY);

        buttonNewGameExtremelyEasy.setText("Extremely easy");
        buttonNewGameExtremelyEasy.setPreferredSize(new java.awt.Dimension(180, 45));

        buttonNewGameEasy.setText("Easy");
        buttonNewGameEasy.setPreferredSize(new java.awt.Dimension(180, 45));

        buttonNewGameMedium.setText("Medium");
        buttonNewGameMedium.setPreferredSize(new java.awt.Dimension(180, 45));

        buttonNewGameDifficult.setText("Diffifult");
        buttonNewGameDifficult.setPreferredSize(new java.awt.Dimension(180, 45));

        buttonNewGameEvil.setText("Evil");
        buttonNewGameEvil.setPreferredSize(new java.awt.Dimension(180, 45));

        lable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lable.setText("Pick one level");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonNewGameMedium, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonNewGameDifficult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonNewGameEvil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonNewGameExtremelyEasy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonNewGameEasy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lable)
                .addGap(18, 18, 18)
                .addComponent(buttonNewGameExtremelyEasy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonNewGameEasy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonNewGameMedium, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonNewGameDifficult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonNewGameEvil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonClicked(int index) {
        final PuzzleFactory.GameDifficulties difficulties = PuzzleFactory.GameDifficulties.values()[index];
        if (this.onGameDifficultiesSelected != null) {
            this.onGameDifficultiesSelected.onGameDifficultiesSelected(difficulties);
        }
        this.dispose();
    }

    public void setOnGameDifficultiesSelected(OnGameDifficultiesSelected onGameDifficultiesSelected) {
        this.onGameDifficultiesSelected = onGameDifficultiesSelected;
    }
    
    private JButton[] buttons = null;
    private OnGameDifficultiesSelected onGameDifficultiesSelected;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonNewGameDifficult;
    private javax.swing.JButton buttonNewGameEasy;
    private javax.swing.JButton buttonNewGameEvil;
    private javax.swing.JButton buttonNewGameExtremelyEasy;
    private javax.swing.JButton buttonNewGameMedium;
    private javax.swing.JLabel lable;
    // End of variables declaration//GEN-END:variables
}
