/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ctu.cit.sudoku.Views;

import edu.ctu.cit.sudoku.Models.Puzzle;
import java.awt.GridLayout;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.event.WindowEvent;
import javax.swing.JButton;
import javax.swing.plaf.basic.BasicArrowButton;

/**
 *
 * @author charlie
 */
public class NumberChooser extends javax.swing.JFrame {

    public interface NumberSelected {

        public void numberSelected(int number);
    }

    /**
     * Creates new form NumberChooser
     */
    private JButton[][] numberButtons = new JButton[3][3];
    private NumberSelected numberSelected;

    public NumberChooser() {
        initComponents();
        addButtons();
    }

    private void addButtons() {
        int label = 1;
        GridLayout layout = new GridLayout(3, 3);
        panel.setLayout(layout);
        for (int i = 0; i < 3; i++) {
            for (int j = 0; j < 3; j++) {
                numberButtons[i][j] = new JButton();
                numberButtons[i][j].setText("" + label++);
                numberButtons[i][j].addMouseListener(this.implementMouseEventListenerForNumberButtons(i, j));
                panel.add(numberButtons[i][j]);
            }
        }
    }

    private MouseListener implementMouseEventListenerForNumberButtons(final int i, final int j) {
        return new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (numberSelected != null) {
                    numberSelected.numberSelected(Integer.parseInt(numberButtons[i][j].getText()));
                }
                NumberChooser.this.dispatchEvent(new WindowEvent(NumberChooser.this, WindowEvent.WINDOW_CLOSING));                
            }

            @Override
            public void mousePressed(MouseEvent e) {
            }

            @Override
            public void mouseReleased(MouseEvent e) {
            }

            @Override
            public void mouseEntered(MouseEvent e) {
            }

            @Override
            public void mouseExited(MouseEvent e) {
            }
        };
    }

    public void setNumberSelected(NumberSelected numberSelected) {
        this.numberSelected = numberSelected;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 159, Short.MAX_VALUE)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 106, Short.MAX_VALUE)
        );

        getContentPane().add(panel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
}
